/* Autogenerated file. Do not edit manually. */

import { defineComponent, Type as RecsType, World } from "@latticexyz/recs";

export function defineContractComponents(world: World) {
  return {
    Piece: (() => {
      const name = "Piece";
      return defineComponent(
        world,
        {
          kind: RecsType.T,
          color: RecsType.T,
          is_alive: RecsType.Boolean,
        },
        {
          metadata: {
            name: name,
          },
        }
      );
    })(),
    Position: (() => {
      const name = "Position";
      return defineComponent(
        world,
        {
          x: RecsType.Number,
          y: RecsType.Number,
        },
        {
          metadata: {
            name: name,
          },
        }
      );
    })(),
    PlayersId: (() => {
      const name = "PlayersId";
      return defineComponent(
        world,
        {
          white: RecsType.Number,
          black: RecsType.Number,
        },
        {
          metadata: {
            name: name,
          },
        }
      );
    })(),
    Game: (() => {
      const name = "Game";
      return defineComponent(
        world,
        {
          status: RecsType.Boolean,
          winner: RecsType.T,
        },
        {
          metadata: {
            name: name,
          },
        }
      );
    })(),
    GameTurn: (() => {
      const name = "GameTurn";
      return defineComponent(
        world,
        {
          turn: RecsType.T,
        },
        {
          metadata: {
            name: name,
          },
        }
      );
    })(),
  };
}
